import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` text-[#1F2937] font-sans${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <div className="max-w-7xl mx-auto" >
          <Header />
          <div className="md:py-3 px-4  " >
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
